name: 'Deploy Resources'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy Resources'
        run: curl -X POST ${{ secrets.BUILD_HOOK }}
